### ISSUE TITLE
UI is messed up when opening SabNzbd from Sabconnect

### ISSUE THREAD

**Issue by TheBigC53** [gboudreau/sabconnectplusplus#167] opened 2017-09-23 15:32 UTC
Same behaviour in Chrome and Firefox. Sabnzbd opens just fine from a bookmark.

https://imgur.com/a/MwpvX

Any way to get the default UI to show up again?

**Comment by gboudreau** [comment] 2017-09-23 16:20
Duplicate of #165

**Closed by gboudreau** 2017-09-23 16:20 UTC
